baseURL: "http://myprogrammerpersonality.github.io/"
languageCode: en-us
Title: "Ali's Blog"
Description: "Bio & Info"
paginate: 5
theme: PaperMod
disqusShortname: Ali

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Ali Yazdizadeh
  description: "Bio & Info"
  keywords: [Blog, Biology, Programming, Bioinformatics, Bioinformatic, Yazdizadeh]
  author: Ali Yazdizadeh
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  enableEmoji: true
  comments: true

  # post
  ShowReadingTime: true
  ShowShareButtons: true

  # introduction
  homeInfoParams:
    Title: "Ali Yazdizadeh"
    Content: "It supposed to be my personal blog!"

  # social-buttons
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/ali-yazdizadeh/"
    - name: github
      url: "https://github.com/myprogrammerpersonality"
    - name: email
      url: "mailto:aliyzd1379@gmail.com"

permalinks:
  posts: /:year/:month/:title/

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
